OnClocService.Portal/Areas/Systems/Pages/PageRegistry/CreatePage.cshtml.cs
#nullable disable

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using OnClocService.Core.Attributes;
using OnClocService.Core.Constants;
using OnClocService.Core.Entities.Systems;
using OnClocService.Domain.DataModels.Systems;
using OnClocService.Domain.Interfaces.Systems;
using OnClocService.Infrastructure.Extensions.Systems;
using OnClocService.Portal.Areas.Systems.PageViews;

namespace OnClocService.Portal.Areas.Systems.Pages.PageRegistry;

[SystemsAuthorize(SysPolicy.Inputter, SysPrivilege.WriteRecord)]
public class CreatePageModel(IPageManagerService pageManager) : PageModel
{
    private readonly IPageManagerService _PageManager = pageManager;
    private readonly string _MessageKey = "Feedback";

    [BindProperty]
    public PageProfile PageProfile { get; set; }
    public SelectList ModulesList { get; set; }
    public ModulePageLinks PageLinks { get; set; }

    public IActionResult OnGet()
    {
        var modulesListSelectedItem = "M0100";
        var httpRequest = PageContext.HttpContext.Request;
        PageLinks = _PageManager.GetPageLinksByRequest(httpRequest);
        ModulesList = _PageManager.GetOrderedListOfModules(modulesListSelectedItem);
        ViewData.Add("ListOfModules", ModulesList);
        return Page();
    }

    public async Task<IActionResult> OnPostCreateAsync()
    {

        var messageType = TemporaryStorage.MessageType.info;
        var messageText = "add new page ";

        if(!ModelState.IsValid)
        {
            messageText += "failed: invalid model";
            TemporaryStorage.AddFeedback(TempData, _MessageKey, messageType, messageText);
            return Page();
        }

        if (PageProfile == null)
        {
            messageText += "failed: details missing";
            messageType = TemporaryStorage.MessageType.warning;
            TemporaryStorage.AddFeedback(TempData, _MessageKey, messageType, messageText);
            return Page();
        }
        var selectedModuleId = PageProfile.SystemsModuleId;
        PredictedPageIdentifier predictedPage = _PageManager.GenerateNewPageIdentifier(selectedModuleId);
        var systemsPage = new SystemsPage() 
        {
            SystemsPageID = predictedPage.Id,
            Index = predictedPage.Index,
            SystemsModuleId = PageProfile.SystemsModuleId,
            AspParentFolder = PageProfile.ModuleFolder,
            AspPage = PageProfile.AspPage,
            Name = PageProfile.PageName,
            Title = PageProfile.PageTitle,
            Description = PageProfile.PageDescription ??= "",
            IconClass = PageProfile.IconClass ??= "",
            IsDefaultPage = PageProfile.IsDefaultPage,
            ShowInMenu = PageProfile.ShowInMenu,
            EnableMenuItem = PageProfile.EnableMenuItem
        };
        bool jobDone = await _PageManager.AddSystemsPageAsync(systemsPage);
        if (!jobDone)
        {
            messageText += "failed: data error";
            messageType = TemporaryStorage.MessageType.danger;
            TemporaryStorage.AddFeedback(TempData, _MessageKey, messageType, messageText);
            return Page();
        }

        messageText += "was successful";
        messageType = TemporaryStorage.MessageType.success;
        TemporaryStorage.AddFeedback(TempData, _MessageKey, messageType, messageText);
        var listPages = PageLinks.ModulePages["ListPages"].ToString();
        return RedirectToPage(listPages);
    }
}

OnClocService.Portal/Areas/Systems/Pages/PageRegistry/ListPages.cshtml.cs
#nullable disable

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using OnClocService.Core.Attributes;
using OnClocService.Core.Constants;
using OnClocService.Core.Entities.Systems;
using OnClocService.Domain.DataModels.Systems;
using OnClocService.Domain.Interfaces.Systems;
using OnClocService.Infrastructure.Extensions.Systems;

namespace OnClocService.Portal.Areas.Systems.Pages.PageRegistry;

[SystemsAuthorize(SysPolicy.Observer, SysPrivilege.ReadRecord)]
public class ListPagesModel(IPageManagerService pageManager, IOptions<SystemsApplicationOptions> applicationOptions) : PageModel
{
    private readonly IPageManagerService _PageManager = pageManager;
    private readonly IOptions<SystemsApplicationOptions> _ApplicationOptions = applicationOptions;

    internal string PageFileSort { get; set; }
    internal string PageNameSort { get; set; }
    internal string PageFilter { get; set; }
    internal string PageSort { get; set; }
    internal PaginatedList<SystemsPage> ListPages { get; set; }
    internal ModulePageLinks PageLinks { get; set; }

    public async Task<IActionResult> OnGetAsync(string sortBy, string findBy, string filterBy, int? pageIndex)
    {
        PageLinks = _PageManager.GetPageLinksByRequest(PageContext.HttpContext.Request);
        var systemPages = _PageManager.GetAllPages;
        if (systemPages.Any())
        {
            PageSort = sortBy;
            PageFileSort = string.IsNullOrEmpty(sortBy) ? "name_descend" : "";
            PageNameSort = sortBy == "Page" ? "page_descend" : "Page";

            if (findBy != null) { pageIndex = 1; } else { findBy = filterBy; }
            filterBy = findBy;
            IQueryable<SystemsPage> pageIquery = from p in systemPages select p;
            if (!string.IsNullOrEmpty(filterBy))
            {
                pageIquery = filterBy switch
                {
                    "hidden" => pageIquery.Where(p => p.ShowInMenu == false),
                    "primary" => pageIquery.Where(p => p.IsDefaultPage == true),
                    "disabled" => pageIquery.Where(p => p.EnableMenuItem == false),
                    _ => pageIquery.Where(p => p.Name.Contains(filterBy) || p.AspPage.Contains(filterBy))
                };
            }

            pageIquery = sortBy switch
            {
                "page_descend" => pageIquery.OrderByDescending(p => p.AspPage),
                "Page" => pageIquery.OrderBy(p => p.AspPage),
                "name_descend" => pageIquery.OrderByDescending(p => p.Name),
                _ => pageIquery.OrderBy(p => p.Name)
            };

            var pageSize = int.Parse(_ApplicationOptions.Value.DefaultPageSize);
            ListPages = await PaginatedList<SystemsPage>.CreatePaginationAsync(pageIquery
                .AsNoTracking().Include(b => b.SystemsModule), pageIndex ?? 1, pageSize);
        }
        return Page();
    }
}

OnClocService.Portal/Areas/Systems/Pages/PageRegistry/ModifyPage.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OnClocService.Portal.Areas.Systems.Pages.PageRegistry;

public class ModifyPageModel : PageModel
{
    public void OnGet()
    {
    }
}

OnClocService.Portal/Areas/Systems/Pages/PageRegistry/RemovePage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OnClocService.Portal.Areas.Systems.Pages.PageRegistry
{
    public class RemovePageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

OnClocService.Portal/Areas/Systems/Pages/PageRegistry/ShowPage.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OnClocService.Portal.Areas.Systems.Pages.PageRegistry;

public class ShowPageModel : PageModel
{
    public void OnGet()
    {
    }
}

OnClocService.Portal/Areas/Systems/Pages/PageRegistry/CreatePage.cshtml
@page
@model CreatePageModel
@{
    var ModuleName = Model.PageLinks.ModuleName;
    var ListPages = Model.PageLinks.ModulePages["ListPages"];
}


<div class="card">
    <div class="card-body">
        <h4 class="card-title">Page Details | enter new page details below to create a new navigation page</h4>
        <form id="SystemsPageToCreate" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="table">
                <div class="row g-3">
                    <div class="col-6">
                        <div class="mb-3 form-floating">
                            <select asp-for="PageProfile.SystemsModuleId" class="form-control" asp-items="Model.ModulesList">
                            </select>
                            <label asp-for="PageProfile.SystemsModuleId" class="form-label"></label>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="mb-3 form-floating">
                            <input asp-for="PageProfile.ModuleFolder" class="form-control" />
                            <label asp-for="PageProfile.ModuleFolder" class="form-label"></label>
                            <span asp-validation-for="PageProfile.ModuleFolder" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row g-3">
                    <div class="col-6">
                        <div class="mb-3 form-floating">
                            <input asp-for="PageProfile.PageName" class="form-control" />
                            <label asp-for="PageProfile.PageName" class="form-label"></label>
                            <span asp-validation-for="PageProfile.PageName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="mb-3 form-floating">
                            <input asp-for="PageProfile.AspPage" class="form-control" />
                            <label asp-for="PageProfile.AspPage" class="form-label"></label>
                            <span asp-validation-for="PageProfile.AspPage" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row g-3">
                    <div class="col-4">
                        <div class="mb-3 form-floating">
                            <input asp-for="PageProfile.PageTitle" class="form-control" />
                            <label asp-for="PageProfile.PageTitle" class="form-label"></label>
                            <span asp-validation-for="PageProfile.PageTitle" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-8">
                        <div class="mb-3 form-floating">
                            <input asp-for="PageProfile.PageDescription" class="form-control" />
                            <label asp-for="PageProfile.PageDescription" class="form-label"></label>
                            <span asp-validation-for="PageProfile.PageDescription" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row g-3">
                    <div class="col-3">
                        <div class="mb-3 form-floating">
                            <input asp-for="PageProfile.IconClass" class="form-control" />
                            <label asp-for="PageProfile.IconClass" class="form-label"></label>
                            <span asp-validation-for="PageProfile.IconClass" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-9">
                        <div class="">
                            <div class="d-inline form-group float-end">
                                <div class="form-check-inline mb-3">
                                    <input type="checkbox" asp-for="PageProfile.EnableMenuItem" class="form-check-input" />
                                    <label class="form-check-label small">
                                        @Html.DisplayNameFor(model => model.PageProfile.EnableMenuItem)
                                    </label>
                                </div>
                                <div class="form-check-inline mb-3">
                                    <input type="checkbox" asp-for="PageProfile.ShowInMenu" class="form-check-input" />
                                    <label class="form-check-label small">
                                        @Html.DisplayNameFor(model => model.PageProfile.ShowInMenu)
                                    </label>
                                </div>
                                <div class="form-check-inline mb-3">
                                    <input type="checkbox" asp-for="PageProfile.IsDefaultPage" class="form-check-input" />
                                    <label class="form-check-label small">
                                        @Html.DisplayNameFor(model => model.PageProfile.IsDefaultPage)
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="card-footer">
        <div class="g-2 p-2">
            <div class="d-inline">
                <a class="btn btn-outline-dark" asp-area="@ModuleName" asp-page="@ListPages.Url"
                   data-bs-toggle="tooltip" data-bs-custom-class="bis-tooltip" data-bs-title="@ListPages.Description">
                    <span><i class="fa-solid fa-chevron-left">&nbsp;</i></span>
                </a>
            </div>
            <div class="d-inline form-group float-end">
                <button class="btn btn-outline-info" type="button" data-bs-target="#batchUpload"
                        data-bs-toggle="modal" data-bs-custom-class="bis-tooltip" data-bs-title="batch file upload">
                    <span><i class="fa fa-solid fa-file-csv"></i>&nbsp;Batch</span>
                </button>
                <button class="btn btn-outline-success" type="submit" form="SystemsPageToCreate" asp-page-handler="Create"
                        data-bs-toggle="tooltip" data-bs-custom-class="bis-tooltip" data-bs-title="save new page">
                    <span><i class="fa-solid fa-floppy-disk"></i>&nbsp;Save</span>
                </button>
            </div>
        </div>
    </div>
</div>

<!-- Modal: Batch File Upload -->
<div id="batchUpload" class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title fs-5" id="exampleModalLabel">Upload Batch</h5>
                <button type="button" class="btn" data-bs-dismiss="modal" aria-label="Close">
                    <i class="fa-solid fa-xmark"></i>
                </button>
            </div>
            <div class="modal-body">
                <form id="batchUploadForm">
                    <div class="form-group">
                        <label class="form-label">Select batch file to Upload:</label>
                        <input class="form-control" type="file" value="file" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <a class="icon-link icon-link-hover" href="#"
                   data-bs-toggle="tooltip" data-bs-custom-class="bis-tooltip" data-bs-title="download a batch file template">
                    <span><i class="fa-solid fa-download">&nbsp;</i></span>Download Batch File
                </a>
                <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal"
                        data-bs-toggle="tooltip" data-bs-custom-class="bis-tooltip" data-bs-title="close and return add page">
                    <span><i class="fa-solid fa-xmark"></i></span>
                </button>
                <button type="button" class="btn btn-outline-success"
                        data-bs-toggle="tooltip" data-bs-custom-class="bis-tooltip" data-bs-title="upload batch file">
                    <span><i class="fa-solid fa-upload">&nbsp;</i></span>
                </button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

OnClocService.Portal/Areas/Systems/Pages/PageRegistry/ListPages.cshtml
@page
@model ListPagesModel
@{
    int numOfPages = Model.ListPages.TotalPages;
    int nextPageIndex = Model.ListPages.PageIndex + 1;
    int prevPageIndex = Model.ListPages.PageIndex - 1;
    var nextBtnDisabled = !Model.ListPages.HasNextPage ? "disabled" : "";
    var prevBtnDisabled = !Model.ListPages.HasPreviousPage ? "disabled" : "";
    var ModuleName = Model.PageLinks.ModuleName;
    var ThisPage = Model.PageLinks.ModulePages["ListPages"];
    var ShowPage = Model.PageLinks.ModulePages["ShowPage"];
    var CreatePage = Model.PageLinks.ModulePages["CreatePage"];
    var ModifyPage = Model.PageLinks.ModulePages["ModifyPage"];
    var RemovePage = Model.PageLinks.ModulePages["RemovePage"];
}


<div class="card">
    <div class="card-header">
        <a class="d-inline icon" asp-area="@ModuleName" asp-page="@CreatePage.Url"
           data-bs-toggle="tooltip" data-bs-title="@CreatePage.Description">
            <i class="mdi mdi-file-document-plus-outline"></i>
            <span>&nbsp;@CreatePage.Title</span>
        </a>
        <div class="d-inline search-bar float-end">
            <form class="search-form d-flex align-items-center" method="get" asp-area="@ModuleName" asp-page="@ThisPage.Url"
                  data-bs-toggle="tooltip" data-bs-title="search for display name or page file">
                <input class="rounded-start" type="text" name="findBy" value="@Model.PageFilter" placeholder="search" />
                <button class="rounded-end" type="submit" title="search"><i class="mdi mdi-magnify"></i></button>
            </form>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-header">
        <h4 class="card-title d-inline">Pages | <span>@Model.ListPages.TotalItems found.</span></h4>
        <!--    Header -->
        <div class="filter d-inline float-end">
            <a class="icon" href="#" data-bs-toggle="dropdown">
                <span><i class="mdi mdi-dots-vertical">&nbsp;</i></span>
            </a>
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                <li class="dropdown-header text-start">
                    <h6>Filter</h6>
                </li>
                <li><a class="dropdown-item" asp-route-filterBy="hidden" asp-area="@ModuleName" asp-page="@ThisPage.Url">Hidden Pages</a></li>
                <li><a class="dropdown-item" asp-route-filterBy="primary" asp-area="@ModuleName" asp-page="@ThisPage.Url">Default Pages</a></li>
                <li><a class="dropdown-item" asp-route-filterBy="disabled" asp-area="@ModuleName" asp-page="@ThisPage.Url">Disabled Pages</a></li>
            </ul>
        </div>
    </div>
    <!--    Main Body -->
    <div class="card-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        <a asp-route-sortBy="@Model.PageNameSort" asp-route-filterBy="@Model.PageFilter"
                           asp-area="@ModuleName" asp-page="@ThisPage.Url">
                            <i class="fa-solid fa-sort">&nbsp;</i>
                            @Html.DisplayNameFor(model => model.ListPages[0].Name)
                        </a>
                    </th>
                    <th>
                        <a asp-route-sortBy="@Model.PageFileSort" asp-route-filterBy="@Model.PageFilter"
                           asp-area="@ModuleName" asp-page="@ThisPage.Url">
                            <i class="fa-solid fa-sort">&nbsp;</i>
                            @Html.DisplayNameFor(model => model.ListPages[0].AspPage)
                        </a>
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ListPages[0].SystemsModule.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ListPages[0].ShowInMenu)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ListPages[0].EnableMenuItem)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ListPages[0].IsDefaultPage)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @{
                    if (Model.ListPages.Any())
                    {
                        foreach (var item in Model.ListPages)
                        {
                            <tr>
                                <td>
                                    <a asp-area="@ModuleName" asp-page="@ShowPage.Url" asp-route-id="@item.SystemsPageID"
                                       title="@ShowPage.Description">
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </a>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.AspPage)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SystemsModule.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ShowInMenu)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.EnableMenuItem)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.IsDefaultPage)
                                </td>
                                <td>
                                    <a class="icon" asp-area="@ModuleName" asp-page="@ModifyPage.Url" asp-route-id="@item.SystemsPageID"
                                       data-bs-toggle="tooltip" data-bs-title="@ModifyPage.Description">
                                        <span><i class="mdi mdi-square-edit-outline">&nbsp;</i></span>
                                    </a> |
                                    <a class="icon" asp-area="@ModuleName" asp-page="@RemovePage.Url" asp-route-id="@item.SystemsPageID"
                                       data-bs-toggle="tooltip" data-bs-title="@RemovePage.Description">
                                        <span><i class="mdi mdi-trash-can-outline">&nbsp;</i></span>
                                    </a>
                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="7">
                                <div class="alert alert-danger" role="alert">
                                    <span class="align-middle">Sorry! no items match your request ...</span>
                                </div>
                            </td>
                        </tr>
                    }
                }

            </tbody>
        </table>
    </div>
    <!--    Footer -->
    <div class="card-footer">
        <nav>
            <ul class="pagination justify-content-end">
                <li class="page-item @prevBtnDisabled">
                    <a class="page-link" asp-route-sortBy="@Model.PageNameSort"
                       asp-route-filterBy="@Model.PageFilter" asp-route-pageIndex="@prevPageIndex">
                        <span><i class="fa-solid fa-chevron-left">&nbsp;</i></span>
                    </a>
                </li>
                @{
                    int firstPage = 1;
                    int maxShowPages = 9;
                    int lastPage = numOfPages;
                    int startPage = numOfPages - maxShowPages;
                    if (startPage > 0)
                    {
                        firstPage = firstPage + (int)Math.Ceiling((decimal)(startPage / 2));
                        lastPage = firstPage + maxShowPages;
                    }
                    int currentPage = Model.ListPages.PageIndex;
                    for (int showPage = firstPage; showPage <= lastPage; showPage++)
                    {
                        string pageNumber = showPage.ToString();
                        string activePage = (currentPage == showPage) ? "active" : "";
                        <li class="page-item @activePage">
                            <a class="page-link" asp-route-sortBy="@Model.PageNameSort" asp-route-filterBy="@Model.PageFilter"
                               asp-route-pageIndex="@showPage.ToString()">@pageNumber</a>
                        </li>
                    }
                }
                <li class="page-item @nextBtnDisabled">
                    <a class="page-link" asp-route-sortBy="@Model.PageNameSort"
                       asp-route-filterBy="@Model.PageFilter" asp-route-pageIndex="@nextPageIndex">
                        <span><i class="fa-solid fa-chevron-right">&nbsp;</i></span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>

OnClocService.Portal/Areas/Systems/Pages/PageRegistry/ModifyPage.cshtml
@page
@model ModifyPageModel
@{
}

OnClocService.Portal/Areas/Systems/Pages/PageRegistry/RemovePage.cshtml
@page
@model OnClocService.Portal.Areas.Systems.Pages.PageRegistry.RemovePageModel
@{
}

OnClocService.Portal/Areas/Systems/Pages/PageRegistry/ShowPage.cshtml
@page
@model ShowPageModel
@{
}